FROM node:20-alpine as build
WORKDIR /app

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ARG VITE_GOOGLE_OIDC_CLIENT_ID
ENV VITE_GOOGLE_OIDC_CLIENT_ID=${VITE_GOOGLE_OIDC_CLIENT_ID}
ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
ARG VITE_APPLE_OIDC_CLIENT_ID
ENV VITE_APPLE_OIDC_CLIENT_ID=${VITE_APPLE_OIDC_CLIENT_ID}
ARG VITE_APPLE_CLIENT_ID
ENV VITE_APPLE_CLIENT_ID=${VITE_APPLE_CLIENT_ID}
ARG VITE_APPLE_REDIRECT_URI
ENV VITE_APPLE_REDIRECT_URI=${VITE_APPLE_REDIRECT_URI}

COPY package*.json ./
RUN npm ci

COPY . ./
RUN npm run build



FROM nginx:1.25-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
